// ============================================================
// DOC TEMPLATES
// Membangun HTML dokumen resmi (bukan crop tampilan aplikasi).
// Dipakai oleh pages/documents.js untuk preview + export PNG/PDF/Print.
// ============================================================
import { safe, rupiah, fmtDate, todayISO, ym, monthLabel, sameMonth, daysUntil } from './utils.js';
import {
  state, getStudent, studentName, programName, teacherName, paymentDueAmount, paymentFinalAmount,
} from './dataStore.js';
import { calcStats, reasonCounts, topFrom, payrollEstimate, unpaidPayments } from './analytics.js';

export const docTypes = () => [
  ['invoice', 'Invoice Pembayaran'],
  ['receipt', 'Kwitansi Pembayaran'],
  ['ownerReport', 'Laporan Bulanan Owner'],
  ['unpaidReport', 'Daftar Siswa Belum Bayar'],
  ['studentMovement', 'Laporan Status Siswa'],
  ['teacherReport', 'Laporan Guru/Pegawai'],
  ['incomeReport', 'Rekap Pemasukan'],
  ['expenseReport', 'Rekap Pengeluaran'],
];

function logoHtml() {
  return state.settings.logoUrl ? `<img src="${state.settings.logoUrl}" alt="Logo">` : 'BM';
}

function signatureHtml() {
  return `<div class="signature"><div>${safe(state.settings.institutionName || 'Bimbel')}<br><br><br><br><b>${safe(state.settings.picName || 'Penanggung Jawab')}</b></div></div>`;
}

function reasonTable(type) {
  const g = reasonCounts(type);
  const rows = Object.entries(g).sort((a, b) => b[1] - a[1]);
  return `<table class="docTable"><thead><tr><th>Alasan</th><th>Jumlah</th></tr></thead><tbody>${rows.map((r) => `<tr><td>${safe(r[0])}</td><td>${r[1]}</td></tr>`).join('') || '<tr><td colspan="2">Belum ada alasan tercatat.</td></tr>'}</tbody></table>`;
}

function docShell(title, subtitle, body, footerExtra = '') {
  return `<div class="docSheet" id="docSheet">
    <div class="docHeader">
      <div style="display:flex;gap:16px;align-items:center"><div class="docLogo">${logoHtml()}</div><div class="docTitle"><h1>${safe(title)}</h1><p>${safe(subtitle)}</p></div></div>
      <div style="text-align:right"><b>${safe(state.settings.institutionName || 'Bimbel')}</b><br><span style="font-size:12px;color:rgba(255,255,255,.75)">${safe(state.settings.address || '')}</span></div>
    </div>
    <div class="docBody">${body}</div>
    <div class="docFooter"><span>Generated by Bimbel Manager · powered by Hasilin</span><span>${safe(footerExtra || fmtDate(todayISO()))}</span></div>
  </div>`;
}

function docInvoice(docState) {
  const p = state.payments.find((x) => x.id === docState.paymentId) || state.payments[0] || {};
  const s = getStudent(p.studentId);
  const prog = state.programs.find((x) => x.id === p.programId) || {};
  const body = `<div class="docMeta">
      <div class="docBox"><b>Ditagihkan kepada</b>${safe(s.name || '-')}<br>${safe(s.parentName || '-')}<br>${safe(s.parentPhone || '-')}</div>
      <div class="docBox"><b>Detail Invoice</b>No: ${safe(p.invoiceNo || '-')}<br>Tanggal: ${fmtDate(p.date)}<br>Jatuh tempo: ${fmtDate(p.dueDate)}</div>
    </div>
    <table class="docTable"><thead><tr><th>Program</th><th>Periode</th><th>Jenis</th><th>Tagihan</th><th>Diskon</th><th>Terbayar</th><th>Sisa</th></tr></thead>
      <tbody><tr><td>${safe(prog.name || '-')}</td><td>${safe(p.period || '-')}</td><td>${safe(p.packageType || '-')}</td><td>${rupiah(p.amount)}</td><td>${rupiah(p.discount)}</td><td>${rupiah(p.paid)}</td><td><b>${rupiah(paymentDueAmount(p))}</b></td></tr></tbody></table>
    <div class="docSummary"><div><b>Status</b><strong>${safe(p.status || '-')}</strong></div><div><b>Total Tagihan</b><strong>${rupiah(paymentFinalAmount(p))}</strong></div><div><b>Sisa Bayar</b><strong>${rupiah(paymentDueAmount(p))}</strong></div></div>
    <div class="docBox"><b>Catatan</b>${safe(p.note || state.settings.invoiceNote || '-')}</div>
    ${signatureHtml()}`;
  return docShell('INVOICE PEMBAYARAN', 'Tagihan resmi bimbingan belajar', body, p.invoiceNo || '');
}

function docReceipt(docState) {
  const p = state.payments.find((x) => x.id === docState.paymentId) || state.payments[0] || {};
  const s = getStudent(p.studentId);
  const body = `<div class="docMeta">
      <div class="docBox"><b>Sudah diterima dari</b>${safe(s.parentName || '-')}<br>Orang tua/wali dari ${safe(s.name || '-')}</div>
      <div class="docBox"><b>Kwitansi</b>No: KWT-${safe(p.invoiceNo || '-')}<br>Tanggal: ${fmtDate(todayISO())}<br>Metode: ${safe(p.method || '-')}</div>
    </div>
    <div class="docSummary"><div><b>Nominal Diterima</b><strong>${rupiah(p.paid)}</strong></div><div><b>Untuk Periode</b><strong>${safe(p.period || '-')}</strong></div><div><b>Status</b><strong>${safe(p.status || '-')}</strong></div></div>
    <table class="docTable"><tr><th>Program</th><td>${safe(programName(p.programId))}</td></tr><tr><th>Keterangan</th><td>Pembayaran bimbingan belajar ${safe(p.packageType || '')}</td></tr><tr><th>Sisa Tagihan</th><td>${rupiah(paymentDueAmount(p))}</td></tr></table>
    ${signatureHtml()}`;
  return docShell('KWITANSI PEMBAYARAN', 'Bukti pembayaran resmi', body, 'KWT-' + (p.invoiceNo || ''));
}

function docOwnerReport(docState) {
  const m = docState.month || ym();
  const st = calcStats(m);
  const body = `<div class="docSummary"><div><b>Siswa Aktif</b><strong>${st.active}</strong></div><div><b>Pemasukan</b><strong>${rupiah(st.income)}</strong></div><div><b>Estimasi Bersih</b><strong>${rupiah(st.net)}</strong></div></div>
    <table class="docTable"><tr><th>Siswa Baru</th><td>${st.newStudents}</td><th>Siswa Cuti</th><td>${st.cuti}</td></tr><tr><th>Siswa Keluar</th><td>${st.keluar}</td><th>Invoice Belum Lunas</th><td>${st.unpaid.length}</td></tr><tr><th>Pengeluaran Tercatat</th><td>${rupiah(st.expense)}</td><th>Estimasi Beban Gaji</th><td>${rupiah(st.payroll)}</td></tr></table>
    <h3>Alasan Siswa Cuti/Keluar</h3>${reasonTable('students')}
    <h3>Alasan Guru/Pegawai Cuti/Keluar</h3>${reasonTable('teachers')}
    <div class="docBox"><b>Rekomendasi</b>${safe((topFrom(reasonCounts('students')) ? `Fokus evaluasi pada alasan: ${topFrom(reasonCounts('students'))[0]}. ` : '') + 'Perkuat program dengan demand tertinggi dan lakukan follow-up pada siswa belum bayar.')}</div>
    ${signatureHtml()}`;
  return docShell('LAPORAN BULANAN OWNER', monthLabel(m), body, monthLabel(m));
}

function docUnpaidReport() {
  const rows = unpaidPayments();
  const body = `<div class="docSummary"><div><b>Invoice Terbuka</b><strong>${rows.length}</strong></div><div><b>Total Tunggakan</b><strong>${rupiah(rows.reduce((s, p) => s + paymentDueAmount(p), 0))}</strong></div><div><b>Lewat Tempo</b><strong>${rows.filter((p) => daysUntil(p.dueDate) < 0).length}</strong></div></div>
    <table class="docTable"><thead><tr><th>Siswa</th><th>Orang Tua</th><th>Program</th><th>Periode</th><th>Sisa</th><th>Jatuh Tempo</th></tr></thead>
      <tbody>${rows.map((p) => { const s = getStudent(p.studentId); return `<tr><td>${safe(s.name)}</td><td>${safe(s.parentName)}</td><td>${safe(programName(p.programId))}</td><td>${safe(p.period)}</td><td>${rupiah(paymentDueAmount(p))}</td><td>${fmtDate(p.dueDate)}</td></tr>`; }).join('') || '<tr><td colspan="6">Tidak ada tunggakan.</td></tr>'}</tbody></table>`;
  return docShell('DAFTAR SISWA BELUM BAYAR', 'Prioritas penagihan administrasi', body, fmtDate(todayISO()));
}

function docStudentMovement(docState) {
  const s = getStudent(docState.studentId) || state.students[0] || {};
  const body = `<div class="docMeta"><div class="docBox"><b>Data Siswa</b>${safe(s.name || '-')}<br>${safe(s.parentName || '-')}<br>${safe(s.parentPhone || '-')}</div><div class="docBox"><b>Status</b>${safe(s.status || '-')}<br>Tanggal: ${fmtDate(s.statusDate || s.joinDate)}<br>Potensi kembali: ${safe(s.returnPotential || '-')}</div></div>
    <table class="docTable"><tr><th>Tanggal Daftar</th><td>${fmtDate(s.joinDate)}</td><th>Daerah</th><td>${safe(s.area || '-')}</td></tr><tr><th>Sumber Informasi</th><td>${safe(s.source || '-')}</td><th>Usia/Kelas</th><td>${safe(s.schoolLevel || '-')}</td></tr><tr><th>Alasan Cuti/Keluar</th><td colspan="3">${safe(s.statusReason || '-')}</td></tr><tr><th>Catatan</th><td colspan="3">${safe(s.statusNotes || s.notes || '-')}</td></tr></table>
    ${signatureHtml()}`;
  return docShell('LAPORAN STATUS SISWA', 'Riwayat status dan alasan evaluasi', body, s.name || '');
}

function docTeacherReport() {
  const body = `<div class="docSummary"><div><b>Guru/Pegawai Aktif</b><strong>${state.teachers.filter((t) => t.status === 'Aktif').length}</strong></div><div><b>Estimasi Gaji</b><strong>${rupiah(payrollEstimate())}</strong></div><div><b>Cuti/Keluar</b><strong>${state.teachers.filter((t) => ['Cuti', 'Keluar'].includes(t.status)).length}</strong></div></div>
    <table class="docTable"><thead><tr><th>Nama</th><th>Jabatan</th><th>Gaji</th><th>Status</th><th>Alasan</th></tr></thead><tbody>${state.teachers.map((t) => `<tr><td>${safe(t.name)}</td><td>${safe(t.role)}</td><td>${rupiah(t.salaryAmount)}</td><td>${safe(t.status)}</td><td>${safe(t.statusReason || '-')}</td></tr>`).join('')}</tbody></table>
    <h3>Rekap Alasan</h3>${reasonTable('teachers')}`;
  return docShell('LAPORAN GURU & PEGAWAI', 'Evaluasi SDM dan beban gaji', body, fmtDate(todayISO()));
}

function docIncomeReport(docState) {
  const m = docState.month || ym();
  const rows = [
    ...state.incomes.filter((i) => sameMonth(i.date, m)),
    ...state.payments.filter((p) => sameMonth(p.date, m) && Number(p.paid) > 0).map((p) => ({
      date: p.date, category: 'Pembayaran Siswa', description: p.invoiceNo + ' - ' + studentName(p.studentId), amount: p.paid, method: p.method,
    })),
  ];
  const body = `<div class="docSummary"><div><b>Total Pemasukan</b><strong>${rupiah(rows.reduce((s, r) => s + Number(r.amount || 0), 0))}</strong></div><div><b>Transaksi</b><strong>${rows.length}</strong></div><div><b>Periode</b><strong>${monthLabel(m)}</strong></div></div>
    <table class="docTable"><thead><tr><th>Tanggal</th><th>Kategori</th><th>Keterangan</th><th>Metode</th><th>Nominal</th></tr></thead><tbody>${rows.map((r) => `<tr><td>${fmtDate(r.date)}</td><td>${safe(r.category)}</td><td>${safe(r.description)}</td><td>${safe(r.method || '-')}</td><td>${rupiah(r.amount)}</td></tr>`).join('')}</tbody></table>`;
  return docShell('REKAP PEMASUKAN', monthLabel(m), body, monthLabel(m));
}

function docExpenseReport(docState) {
  const m = docState.month || ym();
  const rows = state.expenses.filter((e) => sameMonth(e.date, m));
  const body = `<div class="docSummary"><div><b>Total Pengeluaran</b><strong>${rupiah(rows.reduce((s, r) => s + Number(r.amount || 0), 0))}</strong></div><div><b>Estimasi Gaji</b><strong>${rupiah(payrollEstimate())}</strong></div><div><b>Transaksi</b><strong>${rows.length}</strong></div></div>
    <table class="docTable"><thead><tr><th>Tanggal</th><th>Kategori</th><th>Keterangan</th><th>Pegawai</th><th>Nominal</th></tr></thead><tbody>${rows.map((r) => `<tr><td>${fmtDate(r.date)}</td><td>${safe(r.category)}</td><td>${safe(r.description)}</td><td>${safe(r.employeeId ? teacherName(r.employeeId) : '-')}</td><td>${rupiah(r.amount)}</td></tr>`).join('')}</tbody></table>`;
  return docShell('REKAP PENGELUARAN', monthLabel(m), body, monthLabel(m));
}

export function buildDocument(docState) {
  switch (docState.type) {
    case 'receipt': return docReceipt(docState);
    case 'ownerReport': return docOwnerReport(docState);
    case 'unpaidReport': return docUnpaidReport(docState);
    case 'studentMovement': return docStudentMovement(docState);
    case 'teacherReport': return docTeacherReport(docState);
    case 'incomeReport': return docIncomeReport(docState);
    case 'expenseReport': return docExpenseReport(docState);
    default: return docInvoice(docState);
  }
}
